### ISSUE TITLE
InvalidArgumentException: 'item_id' is not valid as special value

### ISSUE THREAD

**Issue by DBinaghi** [GonCuesMa/CollectionFiles#3]
Hi.
Installed and activated the plugin, after uploading a picture associated to a Collection, any attempt to access the SHOW page for that specific Collection throws the following error:

```
InvalidArgumentException: 'item_id' is not valid as a special value, in C:\xampp\htdocs\omeka\application\libraries\Omeka\Record\AbstractRecord.php:352
Stack trace:
#0 C:\xampp\htdocs\omeka\plugins\CollectionFiles\models\CollectionFile.php(150): Omeka_Record_AbstractRecord->getProperty('item_id')
#1 C:\xampp\htdocs\omeka\application\views\helpers\Metadata.php(169): CollectionFile->getProperty('item_id')
#2 C:\xampp\htdocs\omeka\application\views\helpers\Metadata.php(144): Omeka_View_Helper_Metadata->_getRecordMetadata(Object(CollectionFile), 'item_id')
#3 C:\xampp\htdocs\omeka\application\views\helpers\Metadata.php(73): Omeka_View_Helper_Metadata->_getText(Object(CollectionFile), 'item_id')
#4 C:\xampp\htdocs\omeka\application\libraries\Zend\View\Abstract.php(350): Omeka_View_Helper_Metadata->metadata(Object(CollectionFile), 'item_id', Array)
#5 C:\xampp\htdocs\omeka\application\libraries\globals.php(2062): Zend_View_Abstract->__call('metadata', Array)
#6 C:\xampp\htdocs\omeka\plugins\HideFiles\HideFilesPlugin.php(263): metadata(Object(CollectionFile), 'item_id')
#7 C:\xampp\htdocs\omeka\plugins\HideFiles\HideFilesPlugin.php(301): HideFilesPlugin->_isFileHidden(Object(CollectionFile))
#8 C:\xampp\htdocs\omeka\application\libraries\Omeka\Plugin\Broker.php(266): HideFilesPlugin->filterFileMarkupOptions(Array, Array)
#9 C:\xampp\htdocs\omeka\application\libraries\globals.php(324): Omeka_Plugin_Broker->applyFilters('file_markup_opt...', Array, Array)
#10 C:\xampp\htdocs\omeka\application\views\helpers\FileMarkup.php(540): apply_filters('file_markup_opt...', Array, Array)
#11 C:\xampp\htdocs\omeka\application\libraries\globals.php(1444): Omeka_View_Helper_FileMarkup->fileMarkup(Object(CollectionFile), Array, Array)
#12 C:\xampp\htdocs\omeka\plugins\CollectionFiles\CollectionFilesPlugin.php(253): file_markup(Array)
#13 C:\xampp\htdocs\omeka\application\libraries\Omeka\Plugin\Broker.php(154): CollectionFilesPlugin->hookAdminCollectionsShow(Array)
#14 C:\xampp\htdocs\omeka\application\libraries\globals.php(188): Omeka_Plugin_Broker->callHook('admin_collectio...', Array)
#15 C:\xampp\htdocs\omeka\admin\themes\default\collections\show.php(26): fire_plugin_hook('admin_collectio...', Array)
#16 C:\xampp\htdocs\omeka\application\libraries\Omeka\View.php(114): include('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\omeka\application\libraries\Zend\View\Abstract.php(889): Omeka_View->_run('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\omeka\application\libraries\Zend\Controller\Action\Helper\ViewRenderer.php(912): Zend_View_Abstract->render(NULL)
#19 C:\xampp\htdocs\omeka\application\libraries\Zend\Controller\Action\Helper\ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('collections/sho...', NULL)
#20 C:\xampp\htdocs\omeka\application\libraries\Zend\Controller\Action\Helper\ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#21 C:\xampp\htdocs\omeka\application\libraries\Zend\Controller\Action\HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#22 C:\xampp\htdocs\omeka\application\libraries\Zend\Controller\Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#23 C:\xampp\htdocs\omeka\application\libraries\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#24 C:\xampp\htdocs\omeka\application\libraries\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#25 C:\xampp\htdocs\omeka\application\libraries\Zend\Application\Bootstrap\Bootstrap.php(106): Zend_Controller_Front->dispatch()
#26 C:\xampp\htdocs\omeka\application\libraries\Zend\Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#27 C:\xampp\htdocs\omeka\application\libraries\Omeka\Application.php(73): Zend_Application->run()
#28 C:\xampp\htdocs\omeka\admin\index.php(28): Omeka_Application->run()
#29 {main}
```

**Comment by DBinaghi** [comment]
Ok, found out the issue: there's a conflict with another plugin, HideFiles; if this last is deactivated, yours works fine.
